server:
  port: 8080
logging:
  level:
    root: info
    com.jarvis.report: warn
  file:
    name: logs/system.log
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/report?serverTimezone=UTC&useSSL=false
    username: root
    password: TangHui123#
#    druid数据库连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 # 初始建立物理连接的个数
      min-idle: 5 # 最小连接池数量
      max-active: 20 # 最大连接池数量
      max-wait: 60000 # 获取连接时最大等待时间,毫秒
      time-between-eviction-runs-millis: 60000 # 配置间隔多久进行一次检测,检测需要关闭的空闲连接,毫秒
      min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存时间,毫秒
      validation-query: SELECT 1 # 检测连接是否有效
      test-while-idle: true # 申请连接的时候检测,如果空闲时间大于time-between-eviction-runs-millis,执行validation-query
      test-on-borrow: false # 申请连接的时候执行validation-query检测连接是否有效,true降低性能
      test-on-return: false # 归还连接的时候执行validation-query检测连接是否有效,true降低性能
      pool-prepared-statements: true # 打开PSCahce,指定每个连接上pscache大小
      max-pool-prepared-statement-per-connection-size: 20 # 启用pscache大小
      filter: stat,wall,slf4j # 配置拦截的filters,去掉后监控界面sql无法统计,wall用于防火墙
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000 # 慢sql记录,mergesql功能
      web-stat-filter:  # 采集web-jdbc关联的监控数据
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        allow: 127.0.0.1,192.168.52.136 # ip白名单
        deny: 192.168.52.130  # 黑名单(存在共同时,deny优先于allow)
        reset-enable: false
        login-username: admin # localhost:port/druid/
        login-password: admin
        enabled: true